# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Abraham's Blog
SEOTitle: 杨杨的博客 | Abraham's Blog
header-img: img/banner.jpg
email: abram.yang@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  copyright &copy; 2018 AbrahamYang All Rights Reserved.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://abraham-y.github.io" # the base hostname & protocol for your site, e.g. http://example.com

github_repo: "https://github.com/abraham-y/abraham-y.github.io.git" # you code repository


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Goals determine what you going to be!"
sidebar-avatar: /img/about-BY-gentle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`


# SNS settings
RSS: false
weibo_username:     rambodec
twitter_username:   abraham_qw
github_username:    abraham-y
facebook_username:  abraham.y8

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
markdown: kramdown
# theme: minima
# plugins:
#   - jekyll-feed

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# gems: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important


# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
# gitalk:
#   enable: true    #是否开启Gitalk评论
#   clientID: f2c84e7629bb1446c1a4                            #生成的clientID
#   clientSecret: ca6d6139d1e1b8c43f8b2e19492ddcac8b322d0d    #生成的clientSecret
#   repo: qiubaiying.github.io    #仓库名称
#   owner: qiubaiying    #github用户名
#   admin: qiubaiying
#   distractionFreeMode: true #是否启用类似FB的阴影遮罩

# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: af3e1518f33c39a40d0d551779c9014c

# Google Analytics
ga_track_id: 'UA-128737324-1'            # Format: UA-xxxxxx-xx
ga_domain: auto                         # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
# friends: [
#     {
#         title: "WY",
#         href: "http://zhengwuyang.com"
#     },{
#         title: "简书·BY",
#         href: "http://www.jianshu.com/u/e71990ada2fd"
#     },{
#         title: "Apple",
#         href: "https://apple.com"
#     },{
#         title: "Apple Developer",
#         href: "https://developer.apple.com/"
#     }
# ]







# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
